const sceneEl=document.querySelector('#scene'), scene=new THREE.Scene(); scene.background=new THREE.Color(0xd7dde0);
const camera=new THREE.PerspectiveCamera(34,1,.1,1000); camera.position.set(9,8,11);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=.82; sceneEl.appendChild(renderer.domElement);
const controls=new THREE.OrbitControls(camera,renderer.domElement); controls.target.set(0,.5,0); controls.enableDamping=true; controls.dampingFactor=.08; controls.minDistance=5; controls.maxDistance=24; controls.maxPolarAngle=Math.PI/2.05;
scene.add(new THREE.HemisphereLight(0xffffff,0xaab4b7,1.15)); const keyLight=new THREE.DirectionalLight(0xffffff,1.8); keyLight.position.set(-6,13,8); keyLight.castShadow=true; keyLight.shadow.mapSize.set(2048,2048); scene.add(keyLight);
const base=new THREE.Mesh(new THREE.BoxGeometry(10.4,.22,8.2),new THREE.MeshStandardMaterial({color:0x9ca8ad,roughness:.9})); base.position.y=-.16; base.receiveShadow=true; scene.add(base);
const grid=new THREE.GridHelper(10,20,0x86949b,0xb3bdc0); grid.position.y=-.04; grid.scale.z=.8; scene.add(grid); const buildGroup=new THREE.Group(); scene.add(buildGroup);
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(), unit=.62, brickHeight=.48;
const colors={red:{hex:0xc91a09,label:'Sunset red'},yellow:{hex:0xf2cd37,label:'Sunshine yellow'},blue:{hex:0x0055bf,label:'Ocean blue'},green:{hex:0x237841,label:'Leaf green'},orange:{hex:0xfe8a18,label:'Bright orange'},purple:{hex:0x6e3f98,label:'Playful purple'},white:{hex:0xf2f2f2,label:'Cloud white'},black:{hex:0x1b2a34,label:'Night black'},'dark-red':{hex:0x720e0f,label:'Dark red'},tan:{hex:0xd7a94b,label:'Warm tan'},'light-blue':{hex:0x9dc3e6,label:'Light blue'},pink:{hex:0xff9fb5,label:'Pink'},lime:{hex:0x9bcf53,label:'Lime green'},brown:{hex:0x7b3f00,label:'Earth brown'},custom:{hex:0xc91a09,label:'Custom color'}};
const types={'brick-2x4':{studsX:4,studsZ:2,h:1},'brick-2x2':{studsX:2,studsZ:2,h:1},'plate-2x4':{studsX:4,studsZ:2,h:.34},'brick-1x2':{studsX:2,studsZ:1,h:1},'brick-1x1':{studsX:1,studsZ:1,h:1},'slope-2x2':{studsX:2,studsZ:2,h:1,slope:true},tnt:{studsX:2,studsZ:2,h:1,tnt:true}};
let selectedType='brick-2x4',selectedColor='red',bricks=[],effects=[];
const wheel=document.querySelector('#color-wheel'),wheelCursor=document.querySelector('#color-wheel-cursor'),wheelContext=wheel.getContext('2d');
function hsvToHex(h,s,v=1){const i=Math.floor(h*6),f=h*6-i,p=v*(1-s),q=v*(1-f*s),t=v*(1-(1-f)*s),rgb=[[v,t,p],[q,v,p],[p,v,t],[p,q,v],[t,p,v],[v,p,q]][i%6];return (Math.round(rgb[0]*255)<<16)|(Math.round(rgb[1]*255)<<8)|Math.round(rgb[2]*255);}
function drawWheel(){const size=wheel.width,image=wheelContext.createImageData(size,size),center=size/2,radius=center-5;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const dx=x-center,dy=y-center,dist=Math.sqrt(dx*dx+dy*dy),index=(y*size+x)*4;if(dist<=radius){const hue=(Math.atan2(dy,dx)/(Math.PI*2)+1)%1,sat=dist/radius,hex=hsvToHex(hue,sat),r=hex>>16&255,g=hex>>8&255,b=hex&255;image.data[index]=r;image.data[index+1]=g;image.data[index+2]=b;image.data[index+3]=255;}}wheelContext.putImageData(image,0,0);}
function pickWheel(event){const rect=wheel.getBoundingClientRect(),scale=wheel.width/rect.width,x=(event.clientX-rect.left)*scale-wheel.width/2,y=(event.clientY-rect.top)*scale-wheel.height/2,radius=wheel.width/2-5,dist=Math.min(Math.sqrt(x*x+y*y),radius),angle=(Math.atan2(y,x)/(Math.PI*2)+1)%1,saturation=dist/radius,hex=hsvToHex(angle,saturation);colors.custom.hex=hex;selectedColor='custom';document.querySelector('#selected-color').textContent='Custom color';document.querySelector('#color-preview').style.background=`#${hex.toString(16).padStart(6,'0')}`;wheelCursor.style.left=`${50+(x/(wheel.width/2))*50}%`;wheelCursor.style.top=`${50+(y/(wheel.height/2))*50}%`;}
drawWheel();document.querySelector('#color-preview').style.background='#c91a09';wheel.addEventListener('pointerdown',e=>{wheel.setPointerCapture(e.pointerId);pickWheel(e);});wheel.addEventListener('pointermove',e=>{if(e.buttons)pickWheel(e);});
function roundedBox(w,h,d){const s=new THREE.Shape(),x=-w/2,y=-h/2,r=.06;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:2,bevelSize:.025,bevelThickness:.025});}
function makeBrick(typeKey,colorKey,position){const t=types[typeKey],mat=new THREE.MeshStandardMaterial({color:t.tnt?0xd71912:colors[colorKey].hex,roughness:.5}),group=new THREE.Group();group.userData={typeKey,colorKey,tnt:!!t.tnt};const width=t.studsX*unit,depth=t.studsZ*unit,height=t.h*brickHeight;let body;
 if(t.slope){const s=new THREE.Shape();s.moveTo(-width/2,0);s.lineTo(width/2,0);s.lineTo(width/2,height);s.lineTo(-width/2,0);const geo=new THREE.ExtrudeGeometry(s,{depth,bevelEnabled:true,bevelSize:.02,bevelThickness:.02});body=new THREE.Mesh(geo,mat);body.position.set(0,0,-depth/2);}else{body=new THREE.Mesh(roundedBox(width,height,depth),mat);body.position.set(0,height/2,-depth/2);}
 body.castShadow=true;body.receiveShadow=true;group.add(body);if(t.tnt){const bandMat=new THREE.MeshStandardMaterial({color:0x20252b,roughness:.65});for(const x of [-width*.28,width*.28]){const band=new THREE.Mesh(new THREE.BoxGeometry(.075,height+.02,depth+.03),bandMat);band.position.set(x,height/2,0);group.add(band);}const labelCanvas=document.createElement('canvas');labelCanvas.width=256;labelCanvas.height=96;const labelCtx=labelCanvas.getContext('2d');labelCtx.fillStyle='#f4d24b';labelCtx.fillRect(4,4,248,88);labelCtx.strokeStyle='#20252b';labelCtx.lineWidth=8;labelCtx.strokeRect(4,4,248,88);labelCtx.fillStyle='#20252b';labelCtx.font='bold 54px Arial';labelCtx.textAlign='center';labelCtx.textBaseline='middle';labelCtx.fillText('TNT',128,51);const label=new THREE.Mesh(new THREE.PlaneGeometry(.82,.31),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(labelCanvas),transparent:true}));label.position.set(0,height*.52,depth/2+.018);group.add(label);const fuse=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.18,10),new THREE.MeshStandardMaterial({color:0x252a2f}));fuse.position.set(0,height+.09,0);group.add(fuse);const spark=new THREE.Mesh(new THREE.SphereGeometry(.065,10,10),new THREE.MeshBasicMaterial({color:0xffad24}));spark.position.set(0,height+.2,0);group.add(spark);}else if(!t.slope){for(let x=0;x<t.studsX;x++)for(let z=0;z<t.studsZ;z++){const stud=new THREE.Mesh(new THREE.CylinderGeometry(.105,.105,.07,16),mat);stud.position.set((x-(t.studsX-1)/2)*unit,(height+.035),(z-(t.studsZ-1)/2)*unit);stud.castShadow=true;group.add(stud);}}group.position.copy(position);return group;}
function explodeTnt(target){if(target.userData.exploding)return;target.userData.exploding=true;const blastRadius=1.7;bricks=bricks.filter(brick=>{const dx=brick.position.x-target.position.x,dy=brick.position.y-target.position.y,dz=brick.position.z-target.position.z,inside=Math.sqrt(dx*dx+dy*dy+dz*dz)<=blastRadius;if(inside)buildGroup.remove(brick);return !inside;});refresh();const origin=target.position.clone().add(new THREE.Vector3(0,.35,0)),ring=new THREE.Mesh(new THREE.RingGeometry(.12,.2,32),new THREE.MeshBasicMaterial({color:0xffad24,transparent:true,opacity:1,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.copy(origin);scene.add(ring);const particles=[];for(let i=0;i<18;i++){const particle=new THREE.Mesh(new THREE.SphereGeometry(.045+Math.random()*.035,8,8),new THREE.MeshBasicMaterial({color:i%2?0xff542f:0xffc52e,transparent:true}));particle.position.copy(origin);scene.add(particle);particles.push({mesh:particle,velocity:new THREE.Vector3((Math.random()-.5)*2.4,.7+Math.random()*1.8,(Math.random()-.5)*2.4)});}effects.push({ring,particles,start:performance.now()});}
function findBrickGroup(object){let current=object;while(current&&current!==buildGroup){if(current.userData&&current.userData.typeKey)return current;current=current.parent;}return null;}
function refresh(){document.querySelector('#brick-count').textContent=bricks.length;document.querySelector('#empty-hint').classList.toggle('hidden',bricks.length>0);document.querySelector('#undo-btn').disabled=bricks.length===0;}
function place(point){const t=types[selectedType],pos=new THREE.Vector3(Math.round(point.x/unit)*unit,Math.max(0,Math.round(point.y/brickHeight))*brickHeight,Math.round(point.z/unit)*unit),brick=makeBrick(selectedType,selectedColor,pos);buildGroup.add(brick);bricks.push(brick);refresh();}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects([base,...buildGroup.children],true);if(!hits.length)return;const hit=hits[0],p=hit.point.clone();if(hit.object!==base){const target=findBrickGroup(hit.object);if(target?.userData.tnt){explodeTnt(target);return;}if(!target)return;p.y=target.position.y+types[target.userData.typeKey].h*brickHeight;}else p.y=0;place(p);});
document.querySelectorAll('.brick-option').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.brick-option.active').classList.remove('active');b.classList.add('active');selectedType=b.dataset.type;}));
document.querySelectorAll('.color-swatch').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.color-swatch.active').classList.remove('active');b.classList.add('active');selectedColor=b.dataset.color;document.querySelector('#selected-color').textContent=colors[selectedColor].label;}));
function undo(){const b=bricks.pop();if(b)buildGroup.remove(b);refresh();}document.querySelector('#undo-btn').addEventListener('click',undo);document.querySelector('#reset-btn').addEventListener('click',()=>{buildGroup.clear();bricks=[];refresh();});window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')document.querySelector('#reset-btn').click();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}});
document.querySelector('#home-view').addEventListener('click',()=>{camera.position.set(9,8,11);controls.target.set(0,.5,0);controls.update();document.querySelector('#top-view').classList.remove('active');document.querySelector('#home-view').classList.add('active');});document.querySelector('#top-view').addEventListener('click',()=>{camera.position.set(0,15,.01);controls.target.set(0,0,0);controls.update();document.querySelector('#home-view').classList.remove('active');document.querySelector('#top-view').classList.add('active');});
document.querySelector('#help-btn').addEventListener('click',()=>document.querySelector('#help-dialog').showModal());document.querySelector('#close-help').addEventListener('click',()=>document.querySelector('#help-dialog').close());
function resize(){const r=sceneEl.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false);}window.addEventListener('resize',resize);resize();function animate(){requestAnimationFrame(animate);const now=performance.now();effects=effects.filter(effect=>{const age=(now-effect.start)/1000;if(age>1){scene.remove(effect.ring);effect.particles.forEach(p=>scene.remove(p.mesh));return false;}const progress=age/1;effect.ring.scale.setScalar(1+progress*4);effect.ring.material.opacity=1-progress;effect.particles.forEach(p=>{p.mesh.position.copy(effect.ring.position).addScaledVector(p.velocity,age);p.velocity.y-=1.7/60;p.mesh.material.opacity=1-progress;});return true;});controls.update();renderer.render(scene,camera);}animate();
